
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dans_multi_pro_db
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none

app:
  auth:
    tokenExpirationMsec: 864000000
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
  jobs-url: http://dev3.dansmultipro.co.id/api/recruitment
  